baseURL = 'https://team.airoverflow.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'nightfall'

[params]
user = "team"
hostname = "airoverflow.com"
sitedescription = 'AirOverflow is a company & a CTF team from Pakistan. We plat CTFs, organize events related to Cyber Security & ofcourse do fun. '
readingTime = true  # Show reading time on post page
published = true  # Show published data on post page
footerHtml = 'CC-0, Built with <a href="https://gohugo.io" class="footerLink">Hugo</a>. Managed by <a href="https://github.com/hash3liZer" class="footerLink">hash3liZer</a>'

  [params.author]
    name = "AirOverflow Team"
    email = "blog@airoverflow.com"

[menu]
  [[menu.header]]
    name = "blogs"
    weight = 0
    url = "/blogs"
  [[menu.header]]
    name = "members"
    weight = 1
    url = "/members"