baseURL = 'https://team.airoverflow.com/'
languageCode = 'en-us'
title = 'AirOverflow Team'
theme = 'nightfall'

[params]
user = "team"
hostname = "airoverflow.com"
sitedescription = 'AirOverflow is a company & a CTF team from Pakistan. We play CTFs, organize events, create challenges and much more. This website is designed for the purpose of publishing our blogs and showcase our team members. '
readingTime = false  # Show reading time on post page
published = true  # Show published data on post page
footerHtml = 'Built with <a href="https://gohugo.io" class="footerLink">Hugo</a>. Managed by <a href="https://github.com/hash3liZer" class="footerLink">hash3liZer</a>'

  [params.author]
    name = "AirOverflow Team"
    email = "blog@airoverflow.com"

[menu]
  [[menu.header]]
    name = "blogs"
    weight = 0
    url = "/blogs"
  [[menu.header]]
    name = "members"
    weight = 1
    url = "/members"

[[params.social]]
key = 0
name = "A CTF Team | cat :flag_pk:"
url = "#"